<?php

return [
    [
        'category' => 'Side Lamp',
        'slug' => 'side-lamp',
        'source' => 'https://buscoachlights.in/side-lamp.html',
        'items' => [
            ['title' => 'Indicator / Flasher Lamp big', 'code' => 'SL-539', 'image' => 'assets/images/products/sl-539.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'Indicator / Flasher Lamp big', 'code' => 'BCL-101', 'image' => 'assets/images/products/bcl-101.jpg', 'details' => ['Bus / Coach', 'LED Lamp']],
            ['title' => 'SIDE LAMP', 'code' => 'SIDE LAMP 12 Inchs', 'image' => 'https://buscoachlights.in/images/side-lamp/slide-lamp-12inch.jpg', 'details' => ['Bus / Coach', 'Car Carriers', 'Available in: Red, Amber, Green, Blue and Clear']],
            ['title' => 'Indicator Single Side', 'code' => 'BCL-105', 'image' => 'https://buscoachlights.in/images/side-lamp/bcl-105.jpg', 'details' => ['Bus / Coach', 'Available in combination of Red & Amber on Single Side & Combination']],
            ['title' => 'Multiple use lamp', 'code' => 'SL-558', 'image' => 'assets/images/products/sl-558.jpg', 'details' => ['Bus / Coach', 'Available in: Red, Amber, Green, Blue and Clear']],
            ['title' => 'Roof Top Marker', 'code' => 'SL-513', 'image' => 'assets/images/products/sl-513.jpg', 'details' => ['Bus / Coach', 'Available in: Red, Amber, Green, Blue and Clear']],
            ['title' => 'Roof Top Marker - Fish shape', 'code' => 'SL-506', 'image' => 'assets/images/products/sl-506.jpg', 'details' => ['Bus / Coach', 'Available in Red, Amber, Blue, Green & Clear']],
            // Previous image: assets/images/products/sl-515.jpg
            ['title' => 'Side Indicator', 'code' => 'SL-515', 'image' => 'assets/images/products/sl-515-indiamart.png', 'details' => ['Bus / Coach', 'Available in combination of Red, Amber & Clear']],
            ['title' => 'Side Indicator', 'code' => 'SL-550', 'image' => 'assets/images/products/sl-550.jpg', 'details' => ['Bus / Coach', 'Available in combination of Red, Amber & Clear']],
            ['title' => 'Side Indicator', 'code' => 'SL-522', 'image' => 'assets/images/products/sl-522.jpeg', 'details' => ['Bus / Coach', 'Available in combination of Red, Amber & Clear']],
            ['title' => 'Side Indicator', 'code' => 'SL-522', 'image' => 'assets/images/products/sl-522.jpeg', 'details' => ['Bus / Coach']],
            ['title' => 'Side Indicator', 'code' => 'SL-522', 'image' => 'assets/images/products/sl-522.jpeg', 'details' => ['Bus / Coach']],
            ['title' => 'Indicator', 'code' => 'SL-567', 'image' => 'assets/images/products/sl-567.jpg', 'details' => ['Bus / Coach', 'Available in Red & Amber on other side']],
            ['title' => 'Side Indicator', 'code' => 'SL-559', 'image' => 'assets/images/products/sl-559.jpg', 'details' => ['Bus / Coach']],
        ],
    ],
    [
        'category' => 'Markers',
        'slug' => 'markers',
        'source' => 'https://buscoachlights.in/markers.html',
        'items' => [
            ['title' => 'Roof Top / Side Marker', 'code' => 'SL-565', 'image' => 'assets/images/products/sl-565.jpg', 'details' => ['Bus / Coach', 'Available in: Red, Amber, Green, Blue and Clear']],
            // Previous image: assets/images/products/sl-517.jpg
            ['title' => 'Roof Top Marker', 'code' => 'SL-517', 'image' => 'assets/images/products/sl-517-indiamart.png', 'details' => ['Bus / Coach', 'Available in: Red-Amber & Red-Clear Combination']],
            ['title' => 'Flap Marker', 'code' => 'SL-519', 'image' => 'assets/images/products/sl-519.jpg', 'details' => ['Bus / Coach', 'Available in: Red, Amber, Green, Blue, Red-Clear, Red-Amber, Amber-Clear Combo']],
            // Previous image: assets/images/products/sl-544.jpg
            ['title' => 'Flap Marker', 'code' => 'SL-544', 'image' => 'assets/images/products/sl-544-indiamart.png', 'details' => ['Bus / Coach', 'Available in: Red, Amber, Green, Blue, Red-Clear, Red-Amber, Amber-Clear Combo']],
            ['title' => 'Flap Marker', 'code' => 'SL-518', 'image' => 'assets/images/products/sl-518.jpg', 'details' => ['Bus / Coach', 'Universal Application Available in Red, Amber, Clear (on either side)']],
            ['title' => 'Flap Marker', 'code' => 'SL-520', 'image' => 'assets/images/products/sl-520.jpg', 'details' => ['Bus / Coach', 'Available in Red, Amber, Clear.']],
            ['title' => 'Roof Top Marker - Fish shape', 'code' => 'BCL-104', 'image' => 'assets/images/products/bcl-104.jpg', 'details' => ['Bus / Coach', 'Available in Red, Amber, Blue, Green & Clear']],
        ],
    ],
    [
        'category' => 'Licence Plate Lamps',
        'slug' => 'licence-plate-lamps',
        'source' => 'https://buscoachlights.in/licence-plate-lamps.html',
        'items' => [
            ['title' => 'No. Plate Light', 'code' => 'AX-703', 'image' => 'assets/images/products/ax-703.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'No. Plate Light', 'code' => 'AX-716', 'image' => 'assets/images/products/ax-716.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'No. Plate Light', 'code' => 'AX-717', 'image' => 'assets/images/products/ax-717.jpeg', 'details' => ['Bus / Coach']],
            ['title' => 'No. Plate Light', 'code' => 'AX-728', 'image' => 'https://buscoachlights.in/images/licence-plate/ax-728.jpg', 'details' => ['Bus / Coach']],
        ],
    ],
    [
        'category' => 'Multiple Use Lamp',
        'slug' => 'multiple-use-lamp',
        'source' => 'https://buscoachlights.in/multiple-use-lamp.html',
        'items' => [
            ['title' => 'Sleep Lamp', 'code' => 'SL-569', 'image' => 'assets/images/products/sl-569.jpg', 'details' => ['Bus / Coach', 'Available in Red, Amber, Blue, Green']],
            ['title' => 'LED Foot Light', 'code' => 'BCL-103', 'image' => 'assets/images/products/bcl-103.jpg', 'details' => ['Bus / Coach', 'Available in: Red, Amber, Green, Blue and Clear']],
            ['title' => 'SIDE LAMP', 'code' => 'AX-727', 'image' => 'assets/images/products/ax-727.jpg', 'details' => ['Bus / Coach', 'Available in: Red, Amber, Green, Blue and Clear']],
        ],
    ],
    [
        'category' => 'Reflex Reflectors',
        'slug' => 'reflex-reflectors',
        'source' => 'https://buscoachlights.in/reflex-reflectors.html',
        'items' => [
            ['title' => 'Reflex Reflectors', 'code' => 'AX-751', 'image' => 'assets/images/products/ax-751.jpg', 'details' => ['Bus / Coach', 'Dim. 65mm x 35mm', 'Available in Red, Amber, Clear']],
            ['title' => 'Reflex Reflectors', 'code' => 'AX-752', 'image' => 'assets/images/products/ax-752.jpg', 'details' => ['Bus / Coach', 'Dim. 80mm With Steel Ring', 'Available in: Red, Amber, Clear']],
            ['title' => 'Reflex Reflectors', 'code' => 'AX-753', 'image' => 'assets/images/products/ax-753.jpg', 'details' => ['Bus / Coach', 'Dim. 90mm x 40mm With two holes at sides for screw tightening', 'Available in Red, Amber, Clear']],
            ['title' => 'Reflex Reflectors', 'code' => 'AX-755', 'image' => 'assets/images/products/ax-755.jpg', 'details' => ['Bus / Coach', 'Dim. 58mm With Steel Ring', 'Available in Red, Amber, Clear']],
            ['title' => 'Reflex Reflectors', 'code' => 'AX-756', 'image' => 'https://buscoachlights.in/images/reflex-reflectors/AX-756.JPG', 'details' => ['Bus / Coach', 'Available in Red, Amber, Clear']],
            ['title' => 'Reflex Reflectors', 'code' => 'AX-757', 'image' => 'assets/images/products/ax-757.jpg', 'details' => ['Bus / Coach', 'Dim. 170mm x 170mm x 170mm', 'Available in Red, Amber, Clear']],
            ['title' => 'Reflex Reflectors', 'code' => 'AX-758', 'image' => 'assets/images/products/ax-758.jpg', 'details' => ['Bus / Coach', 'With four Leg Stand Foldable', 'Available in Red, Amber, Clear']],
            ['title' => 'Reflex Reflectors', 'code' => 'AX-760', 'image' => 'assets/images/products/ax-760.jpg', 'details' => ['Bus / Coach', 'Dim. 102mm x 46mm', 'Available in Red, Amber, Clear']],
            ['title' => 'Reflex Reflectors', 'code' => 'AX-761', 'image' => 'assets/images/products/ax-761.jpeg', 'details' => ['Bus / Coach']],
            ['title' => 'Reflex Reflectors', 'code' => 'AX-762', 'image' => 'assets/images/products/ax-762.jpeg', 'details' => ['Bus / Coach']],
        ],
    ],
    [
        'category' => 'Interior Lamps',
        'slug' => 'interior-lamps',
        'source' => 'https://buscoachlights.in/interior-lamps.html',
        'items' => [
            ['title' => 'Sleep Lamp / roof lamp', 'code' => 'BCL-106', 'image' => 'https://buscoachlights.in/images/interior-lamps/bcl-106.jpg', 'details' => ['Bus / Coach', 'LED']],
            ['title' => 'Interior Lamp with tube', 'code' => 'BCL-107', 'image' => 'https://buscoachlights.in/images/interior-lamps/bcl-107.jpg', 'details' => ['Bus / Coach', 'Available in: 12V / 24V']],
            ['title' => 'Interior Lamp with tube', 'code' => 'BCL-108', 'image' => 'https://buscoachlights.in/images/interior-lamps/bcl-108.jpg', 'details' => ['Bus / Coach', 'Available in: 12V / 24V']],
            ['title' => 'Interior Lamp with tube', 'code' => 'BCL-109', 'image' => 'https://buscoachlights.in/images/interior-lamps/bcl-109.jpg', 'details' => ['Bus / Coach', 'Available in: 12V / 24V']],
            ['title' => 'Interior Lamp with tube', 'code' => 'BCL-110', 'image' => 'https://buscoachlights.in/images/interior-lamps/bcl-110.jpg', 'details' => ['Bus / Coach', 'Available in: 12V / 24V']],
            ['title' => 'Interior Lamp Round', 'code' => 'BCL-115', 'image' => 'https://buscoachlights.in/images/interior-lamps/bcl-115.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'Roof Lamp', 'code' => 'AX-1003', 'image' => 'assets/images/products/ax-1003.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'Roof Lamp', 'code' => 'AX-1004', 'image' => 'assets/images/products/ax-1004.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'Roof Lamp', 'code' => 'AX-1005', 'image' => 'assets/images/products/ax-1005.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'Roof Lamp', 'code' => 'AX-1006', 'image' => 'assets/images/products/ax-1006.jpg', 'details' => ['Bus / Coach']],
            // Previous image: assets/images/products/ax-1008.jpg
            ['title' => 'Roof Lamp', 'code' => 'AX-1008', 'image' => 'assets/images/products/ax-1008-indiamart.png', 'details' => ['Bus / Coach']],
            ['title' => 'Roof Lamp', 'code' => 'AX-1009', 'image' => 'assets/images/products/ax-1009.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'Roof Lamp', 'code' => 'AX-1011', 'image' => 'assets/images/products/ax-1011.jpg', 'details' => ['Bus / Coach']],
        ],
    ],
    [
        'category' => 'Revolving Lights',
        'slug' => 'revolving-lights',
        'source' => 'https://buscoachlights.in/revolving-lights.html',
        'items' => [
            ['title' => 'Revoliving Light Big', 'code' => 'AX-723', 'image' => 'assets/images/products/ax-723.jpg', 'details' => ['Bus / Coach', 'Total Height - 205mm', 'Lens Diameter - 115mm', 'Available in Amber / Red / Blue', 'Available in 12V / 24V.']],
            ['title' => 'Revoliving Light small', 'code' => 'AX-724', 'image' => 'assets/images/products/ax-724.jpg', 'details' => ['Bus / Coach', 'Total Height - 140mm', 'Lens Diameter - 100mm', 'Available in Amber / Red / Blue', 'Available in 12V / 24V.']],
            ['title' => 'Revoliving Light', 'code' => 'AX-729', 'image' => 'https://buscoachlights.in/images/revolving-lights/ax-729.jpg', 'details' => ['Bus / Coach', 'Available in 12V / 24V.', 'Available in Red / Amber / Blue / Lens DIA']],
            ['title' => 'Revoliving Light', 'code' => 'AX-730', 'image' => 'https://buscoachlights.in/images/revolving-lights/ax-730.jpg', 'details' => ['Bus / Coach', 'Available in 12V / 24V.', 'Available in Red / Amber / Blue / Lens DIA', 'Overall Height']],
            ['title' => 'Revoliving Light', 'code' => 'AX-713', 'image' => 'assets/images/products/ax-713.jpg', 'details' => ['Bus / Coach', 'Available in 12V / 24V.', 'Available in Red / Amber / Blue / Lens DIA']],
        ],
    ],
    [
        'category' => 'Clocks',
        'slug' => 'clocks',
        'source' => 'https://buscoachlights.in/clocks.html',
        'items' => [
            ['title' => 'Clock', 'code' => 'DC-001', 'image' => 'https://buscoachlights.in/images/clocks/dc-001.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'Clock', 'code' => 'DC-002', 'image' => 'https://buscoachlights.in/images/clocks/dc-002.jpg', 'details' => ['Bus / Coach']],
        ],
    ],
    [
        'category' => 'LED Lamps',
        'slug' => 'led-lamps',
        'source' => 'https://buscoachlights.in/led-lamps.html',
        'items' => [],
    ],
    [
        'category' => 'Head Lamp',
        'slug' => 'head-lamp',
        'source' => 'https://buscoachlights.in/head-lamp.html',
        'items' => [
            ['title' => 'Head Lamp', 'code' => 'HL-915', 'image' => 'assets/images/products/hl-915.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'Head Lamp', 'code' => 'BHL-101', 'image' => 'https://buscoachlights.in/images/head-lamp/no-image.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'Head Lamp', 'code' => 'BHL-103', 'image' => 'https://buscoachlights.in/images/head-lamp/no-image.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'Head Lamp', 'code' => 'BHL-106', 'image' => 'https://buscoachlights.in/images/head-lamp/no-image.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'Head Lamp', 'code' => 'BHL-139', 'image' => 'https://buscoachlights.in/images/head-lamp/no-image.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'Head Lamp', 'code' => 'BHL-141', 'image' => 'https://buscoachlights.in/images/head-lamp/no-image.jpg', 'details' => ['Bus / Coach']],
            ['title' => 'Head Lamp', 'code' => 'BHL-112', 'image' => 'https://buscoachlights.in/images/head-lamp/no-image.jpg', 'details' => ['Bus / Coach']],
        ],
    ],
];
